import { Midi } from '@tonejs/midi';
import type { MusicalAnalysis, ScoreNote } from './types';

const NAMES=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
export const keyName=(pc:number,mode:'major'|'minor')=>`${NAMES[pc]} ${mode==='major'?'大调':'小调'}`;
export const keyRootMidi=(pc:number)=>60+pc;

function download(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function buildMidiBytes(notes:ScoreNote[],analysis:MusicalAnalysis){const midi=new Midi();midi.header.setTempo(analysis.bpm);midi.header.timeSignatures.push({ticks:0,timeSignature:[analysis.meter,4],measures:0});const track=midi.addTrack();notes.forEach(n=>track.addNote({midi:n.pitchMidi,time:n.startBeat*60/analysis.bpm,duration:n.durationBeats*60/analysis.bpm,velocity:n.amplitude}));return new Uint8Array(midi.toArray())}
export function exportMidi(notes:ScoreNote[],analysis:MusicalAnalysis){download(new Blob([buildMidiBytes(notes,analysis)],{type:'audio/midi'}),'vocal-score.mid')}
export function buildMusicXml(notes:ScoreNote[],a:MusicalAnalysis){const divisions=4;const fifths=[0,7,2,9,4,11,6,1,8,3,10,5].indexOf(a.keyPitchClass);const fifthValue=fifths>6?fifths-12:fifths;let measure=1,body='';for(const n of notes){while(n.startBeat>=measure*a.meter){body+='</measure><measure number="'+(++measure)+'">';}const midi=n.pitchMidi,pc=((midi%12)+12)%12;const map:[string,number][]=[['C',0],['C',1],['D',0],['D',1],['E',0],['F',0],['F',1],['G',0],['G',1],['A',0],['A',1],['B',0]];const [step,alter]=map[pc];body+=`<note><pitch><step>${step}</step>${alter?`<alter>${alter}</alter>`:''}<octave>${Math.floor(midi/12)-1}</octave></pitch><duration>${Math.max(1,Math.round(n.durationBeats*divisions))}</duration><type>${n.durationBeats>=2?'half':n.durationBeats>=1?'quarter':'eighth'}</type></note>`;}return `<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>人声转录结果</work-title></work><part-list><score-part id="P1"><part-name>Vocal</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>${divisions}</divisions><key><fifths>${fifthValue}</fifths><mode>${a.mode}</mode></key><time><beats>${a.meter}</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><direction><sound tempo="${a.bpm}"/></direction>${body}</measure></part></score-partwise>`}
export function exportMusicXml(notes:ScoreNote[],a:MusicalAnalysis){download(new Blob([buildMusicXml(notes,a)],{type:'application/vnd.recordare.musicxml+xml'}),'vocal-score.musicxml')}
